### ISSUE TITLE
Use UmbPack to generate package

### ISSUE THREAD

**Issue by bjarnef** [mastrup/ourHtagEditor#10]
Currently the `grunt-umbraco-package` is used to generate the Umbraco package: https://www.npmjs.com/package/grunt-umbraco-package

This is however not up-to-date with support for e.g. icon url and contributors.
The UmbPack is a great tool to generate the Umbraco package https://github.com/umbraco/UmbPack and can also deploy the package to https://our.umbraco.com

I have used it in the Color Pickr package:
https://github.com/bjarnef/color-pickr

where i have a build command to generate the Umbraco and NuGet package:
https://github.com/bjarnef/color-pickr/blob/master/build/build.cmd

**Comment by mastrup** [comment]
I'll look into this when I have some time on my hands 👌🏻

**Comment by mastrup** [comment]
I now use UmbPack to generate the package 🎉
