### ISSUE TITLE
Feature Request:  Allow removal of all alignment options

### ISSUE THREAD

**Issue by BarryFogarty** [mastrup/ourHtagEditor#15]
Be great if you could disable the alignment selection altogether.  This would keep the UI clean and sensible when you were not offering a choice to your editors.  Great package though!

**Comment by mastrup** [comment]
Thanks, I am glad you like it!

I agree, this would be a nice improvement.
I guess the best approach would be to just hide the alignment options if only one is allowed.
I welcome alternative options, to have the best approach on implementing this.

**Comment by mastrup** [comment]
I have just released version 2.0.1.
Now the property editor hides the alignment option if only one option is allowed on the data type.
If the current selection on the property doesn't match the default, it will auto-select the default option.
