### ISSUE TITLE
Add font icon in custom font file 

### ISSUE THREAD

**Issue by bjarnef** [mastrup/ourHtagEditor#2]
Consider to add a custom font file instead of including entire font awesome library, e.g. by using https://icomoon.io/app/

![image](https://user-images.githubusercontent.com/2919859/38308389-3be48bca-3817-11e8-8b37-bf362922fb6c.png)

And then consider to add a prefix, e.g. `hte` or something elso to avoid it conflict with other packages.
The class name will then be `icon-hte-heading` instead of `icon-heading`.

![image](https://user-images.githubusercontent.com/2919859/38308487-87ef6d0a-3817-11e8-84b2-fea9059644c5.png)

**Comment by mastrup** [comment]
Good idea!
I'll look into it!
