### ISSUE TITLE
Umbraco Cloud / Deploy

### ISSUE THREAD

**Issue by McGlade** [mastrup/ourHtagEditor#4]
Hi Søren,
Really nice package.
Is there an compatible issue with Umbraco Cloud/Courier.  I've found the text heading is being transferred from local to dev, but the tags and style values are not.
Thanks
Martin,

**Comment by mastrup** [comment]
Hi @McGlade,

Noted - I'll try to do a push between environments too se what's going on.

**Comment by mastrup** [comment]
It looks like Deploy doesn't like to move the custom values in the JSON object.
I will look into an alternative way to save them.

**Comment by mastrup** [comment]
I have released a new version that fixes the issue.
