### ISSUE TITLE
UAAS : $scope.control

### ISSUE THREAD

**Issue by stefanoberetta** [mastrup/ourHtagEditor#5]
Awesome plugin!
Maybe it is an Umbraco Deploy issue, i don't know.
It seems all the data stored inside $scope.control doesn't get deployed when using UAAS.
I think moving the tag and the alignment inside $scope.model.value should resolve this.

**Comment by mastrup** [comment]
Thanks! 🤠
This issue has been solved in version 1.0.2 - Go get it! 🎉

After updating the package, existing editors needs to be updated manually by republishing the node where the editor is inserted.

**Comment by stefanoberetta** [comment]
Oops, sorry... My mistake!
Thank you!
