### ISSUE TITLE
Accessibility enhancements of buttons and icons

### ISSUE THREAD

**Issue by bjarnef** [mastrup/ourHtagEditor#9]
There's a few things that could be done to enhance accessibility in the package.

- Add `aria-hidden="true"` to icons (or use `<umb-icon>` which handle this - this require Umbraco 8.8+ though).

- Use `<button type="button">` elements for buttons, e.g. the buttons in prevalue editor.
https://github.com/mastrup/ourHtagEditor/blob/master/app/App_Plugins/HtagGridEditor/views/headline.editor.html#L7-L13

The button element should also have `aria-label` if no button text is visible: https://web.dev/button-name/

**Comment by mastrup** [comment]
I have implemented the `<umb-icon>` directive for icons and switched to use `<button type="button">` in version 2.0.0 for Umbraco 10.
